// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieMania.Data;

#nullable disable

namespace MovieMania.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230726100505_moviemania")]
    partial class moviemania
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MovieMania.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("MovieName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("producer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("releaseDate")
                        .HasColumnType("date");

                    b.Property<double>("ticketPrice")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("MovieName")
                        .IsUnique();

                    b.ToTable("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
